-- El nombre que escribio quien reservo, guardado en el turno.
--
-- Hasta ahora el turno solo apuntaba al jugador (customer), y el nombre del
-- jugador se reescribia con cada reserva hecha con su telefono: alcanzaba con
-- equivocarse un numero para pisarle el nombre a otro en la agenda y en todo
-- su historial. Ahora ese nombre ya no lo cambia cualquiera
-- (CustomerService.findOrCreate), y lo que escribio cada uno queda aca, para
-- que el turno diga quien reservo de verdad y el panel marque la diferencia.
--
-- Nullable a proposito: los turnos de antes de este cambio, y los que genera
-- un turno fijo, no tienen un nombre propio y muestran el del jugador.
ALTER TABLE booking ADD COLUMN booked_name VARCHAR(120);
